spring:
  application:
    name: calculator-service

server:
  port: 8090

management:
  tracing:
    enabled: true
    sampling:
      probability: 1

  otlp:
    tracing:
      endpoint: http://simplest-collector:4318/v1/traces

logging:
  level:
    org.springframework.cloud.sleuth: DEBUG
    io.opentelemetry: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
  pattern:
    level: "[${spring.application.name},%X{traceId},%X{spanId}] %5p"