FROM maven:3.9.6-amazoncorretto-21 AS builder

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests


FROM amazoncorretto:21

WORKDIR /app

COPY --from=builder /app/target/calculator.jar calculator.jar

RUN chmod +x calculator.jar

EXPOSE 8082

ENTRYPOINT ["java", "-jar", "calculator.jar"]